# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
            ],
        ),
    ]
