# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life_class', '0001_initial'),
    ]

    operations = [
    ]
