# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_class', '0002_remove_lifeclass_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeclass',
            name='sex',
            field=models.CharField(max_length=3),
        ),
    ]
