# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_class', '0003_auto_20170711_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifeclass',
            old_name='tags',
            new_name='taga',
        ),
        migrations.AlterField(
            model_name='lifeclass',
            name='sex',
            field=models.CharField(max_length=5),
        ),
    ]
