# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life_class', '0003_auto_20170710_2033'),
        ('life_class', '0002_auto_20170710_1623'),
    ]

    operations = [
    ]
