# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life_class', '0004_auto_20170713_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifeclass',
            old_name='taga',
            new_name='tags',
        ),
    ]
